name: Deploy to Dev ECS

permissions:
  contents: read # Needed to check out code

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [main]

concurrency:
  group: deploy-dev
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    env:
      ECS_CLUSTER: delta
      ECS_SERVICE: delta-dev-blue
    permissions:
      id-token: write # Needed to communicate with AWS

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: mbta/actions/build-push-ecr@f3f7205f8e73dddf983ee234dd93e2b45d3c8a9a # v2.23
        id: build-push
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          docker-repo: ${{ secrets.DOCKER_REPO }}
          docker-additional-tags: dev
      - uses: mbta/actions/deploy-ecs@f3f7205f8e73dddf983ee234dd93e2b45d3c8a9a # v2.23
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          ecs-cluster: ${{ env.ECS_CLUSTER }}
          ecs-service: ${{ env.ECS_SERVICE }}
          docker-tag: ${{ steps.build-push.outputs.docker-tag }}
      - uses: mbta/actions/notify-slack-deploy@f3f7205f8e73dddf983ee234dd93e2b45d3c8a9a # v2.23
        if: ${{ !cancelled() }}
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          job-status: ${{ job.status }}
